---
- name: Install Tailscale
  ansible.builtin.include_tasks: install.yml

- name: Configure Tailscale
  ansible.builtin.include_tasks: configure.yml

- name: Verify Tailscale
  ansible.builtin.include_tasks: verify.yml
