---
openwrt_router_name: mt6000
openwrt_config_dir: /etc/config
openwrt_config_repo_dir: ansible/configs/openwrt
openwrt_snapshot_root: snapshots
openwrt_uci_files:
  - network
  - wireless
  - firewall
  - dhcp
  - system
  - tailscale
openwrt_verify_dns_domain: example.com
openwrt_verify_http_url: https://example.com
openwrt_tailscale_authkey_dcli_path: openwrt/mt6000/tailscale/auth_key
openwrt_tailscale_authkey: >-
  {{ lookup('pipe', 'dcli p --output console title=' + openwrt_tailscale_authkey_dcli_path) }}
openwrt_tailscale_routes:
  - 192.168.8.0/24
