---
all:
  children:
    servers:
      hosts:
        atlas-host:
          ansible_host: 192.168.8.134
          ansible_user: christian
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_port: 22
          ansible_connection: ssh
