all:
  children:
    openwrt:
      hosts:
        mt6000:
          ansible_host: 192.168.8.1
          ansible_user: root
          ansible_port: 22
          ansible_connection: ssh
          ansible_shell_executable: /bin/ash
